env                        = "Dev"
business_unit              = "IT"
services                   = "lab"
location                   = "Australiaeast"
resource_group_name_prefix = "rg"
vmname                     = "vm"
